# Generated by Django 6.1 on 2026-09-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='पूरा नाम')),
                ('phone', models.CharField(max_length=15, verbose_name='फ़ोन नंबर')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ईमेल')),
                ('service', models.CharField(choices=[('kundli', 'कुंडली विश्लेषण (Kundli Analysis)'), ('vastu', 'वास्तु परामर्श (Vastu Consultation)'), ('matchmaking', 'गुण मिलान (Matchmaking)'), ('puja', 'पूजा एवं अनुष्ठान (Puja & Anushthan)'), ('gemstone', 'रत्न परामर्श (Gemstone Advice)'), ('other', 'अन्य (Other)')], max_length=50, verbose_name='सेवा')),
                ('preferred_date', models.DateField(verbose_name='तारीख')),
                ('preferred_time', models.TimeField(verbose_name='समय')),
                ('birth_details', models.TextField(blank=True, null=True, verbose_name='जन्म विवरण')),
                ('message', models.TextField(blank=True, null=True, verbose_name='अतिरिक्त संदेश')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
